# Generated by Django 3.1.4 on 2020-12-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='concact_date',
            new_name='contact_date',
        ),
    ]
